

services:
  gateway:
    build: ./gateway
    env_file: gateway/.env
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - product

    networks:
      - backend
  admin:
    build:
      context: ./admin
    container_name: admin
    ports:
      - "8003:8003"
    networks:
      - backend
  alert:
    build:
      context: ./alert
    container_name: alert
    ports:
      - "8005:8005"
    networks:
      - backend
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3307"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend

  order:
    build:
      context: ./order
    container_name: order
    ports:
      - "8004:8004"
    networks:
      - backend
  product:
    build:
      context: ./product
    container_name: product
    ports:
      - "8001:8001"
    networks:
      - backend

  mongodb_product:
    image: mongo:6.0
    container_name: mongodb_product
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb_product
      MONGO_INITDB_DATABASE: product
    ports:
      - "27018:27017"  # 내부는 항상 27017

    volumes:
      - mongodb_product:/data/db
    networks:
      - backend
  mongodb_brand:
    image: mongo:6.0
    container_name: mongodb_brand
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb_brand
      MONGO_INITDB_DATABASE: brand
    ports:
      - "27020:27017"  # 내부는 항상 27017

    volumes:
      - mongodb_brand:/data/db
    networks:
      - backend
  mongodb_order:
    image: mongo:6.0
    container_name: mongodb_order
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb_order
      MONGO_INITDB_DATABASE: order
    ports:
      - "27019:27017"  # 내부는 항상 27017
    volumes:
      - mongodb_order:/data/db
    networks:
      - backend
  cart:
    build:
      context: ./cart
    container_name: cart
    ports:
      - "8002:8002"
    networks:
      - backend
  mongodb_cart:
    image: mongo:6.0
    container_name: mongodb_cart
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb_cart
      MONGO_INITDB_DATABASE: cart
    ports:
      - "27017:27017"
    volumes:
      - mongodb_cart:/data/db
    networks:
      - backend
volumes:
  mysql:
  mongodb_cart:
  mongodb_product:
  mongodb_order:
  mongodb_brand:
networks:
  backend:
    driver: bridge

