version: '3.8'

services:
  web:
    build: ./gateway
    env_file: gateway/.env

    ports:
      - "8000:8000"
  admin:
    build:
      context: ./admin
    container_name: admin
    ports:
      - "8003:8003"
    networks:
      - msa-network
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql



  order:
    build:
      context: ./order
    container_name: order
    ports:
      - "8004:8004"
    networks:
      - msa-network

  product:
    build:
      context: ./product
    container_name: product
    ports:
      - "8001:8001"
    networks:
      - msa-network
  mongodb_product:
    image: mongo:6.0
    container_name: mongodb_product
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb_product
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db
  cart:
    build:
      context: ./cart
    container_name: cart
    ports:
      - "8002:8002"
    networks:
      - msa-network
  mongodb_cart:
    image: mongo:6.0
    container_name: mongodb_cart
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb_cart
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
networks:
  msa-network:
    driver: bridge